* Generated by MPModelProtoExporter
*   Name             : 
*   Format           : Free
*   Constraints      : 6
*   Variables        : 9
*     Binary         : 0
*     Integer        : 0
*     Continuous     : 9
NAME          
ROWS
 N  COST
 E  auto_c_000000000
 E  auto_c_000000001
 E  auto_c_000000002
 E  auto_c_000000003
 E  auto_c_000000004
 E  auto_c_000000005
COLUMNS
    x1                COST                  -5  auto_c_000000000       1
    x1                auto_c_000000003       1
    x2                auto_c_000000000       1  auto_c_000000004       1
    x3                COST                  -3  auto_c_000000000       1
    x3                auto_c_000000005       1
    x4                COST                  -3  auto_c_000000001       1
    x4                auto_c_000000003       1
    x5                COST                  -7  auto_c_000000001       1
    x5                auto_c_000000004       1
    x6                COST                  -9  auto_c_000000001       1
    x6                auto_c_000000005       1
    x7                COST                  -3  auto_c_000000002       1
    x7                auto_c_000000003       1
    x8                COST                  -5  auto_c_000000002       1
    x8                auto_c_000000004       1
    x9                COST                  -2  auto_c_000000002       1
    x9                auto_c_000000005       1
RHS
    RHS               auto_c_000000000       1  auto_c_000000001       1
    RHS               auto_c_000000002       1  auto_c_000000003       1
    RHS               auto_c_000000004       1  auto_c_000000005       1
BOUNDS
 PL BOUND             x1
 PL BOUND             x2
 PL BOUND             x3
 PL BOUND             x4
 PL BOUND             x5
 PL BOUND             x6
 PL BOUND             x7
 PL BOUND             x8
 PL BOUND             x9
ENDATA
